spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-skeleton


  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
        hbm2ddl.auto: create-drop
    open-in-view: false
    show-sql: false